### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by adx0-a** [ZLaxtert/cc-checkerV4.5#1]
PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /home/kali/cc-checkerV4.5/cli.php(10) : eval()'d code(7) : eval()'d code:84
Stack trace:
#0 /home/kali/cc-checkerV4.5/cli.php(10) : eval()'d code(7): eval()
#1 /home/kali/cc-checkerV4.5/cli.php(10): eval()
#2 {main}
  thrown in /home/kali/cc-checkerV4.5/cli.php(10) : eval()'d code(7) : eval()'d code on line 84
                                                                             
┌──(kali㉿kali)-[~/cc-checkerV4.5]
└─$

**Comment by ZLaxtert** [comment]
There was a problem when you installed PHP, and if you want to run the tool you must have APIKEY.

**Comment by ZLaxtert** [comment]
https://enginetemplates.com/call-to-undefined-function-curl_init/#:~:text=The%20error%20%E2%80%9CCall%20to%20undefined,to%20use%20the%20curl_init%20function.

**Comment by adx0-a** [comment]
ok but what apikey must be in i mean sk_live or what

**Comment by ZLaxtert** [comment]
My tool doesn't need sk_key, it only needs APIKEY. You can get Apikey on my site.

https://darkxcode.site

**Comment by BEST-SMART-WORK** [comment]
your tool not support my country sir

**Comment by ZLaxtert** [comment]
If you have apikey my tool will work in any country.
